# This is a TOML document

title = "TOML Example"

[owner]
name = "Tom Preston-Werner"
dob = 1979-05-27T07:32:00-08:00

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0, string="""Orlando jose
da cunha
Palmeira
""", dict= {test1= 45, 'test2'= false, "test3"= "true", test4 = [ ["delta", "phi"], [3.14], {test1= 45, 'test2'= false, lista = [1], valor = 34, dicio = {x = 1, lista = [1,2,3,4,5,true,false, {k=2, l = [{k=1},{k=2},{k=3}]}]}} ]}}

[servers]

    [servers.alpha]
    ip = "10.0.0.1"
    role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"